name: AutoMerge

on:
  #以下pr类型触发
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  #拉请求审查    
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
  
jobs:
  automerge:    
    name: merge PR to main branch
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: 开始合并
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
          MERGE_LABELS: ''
          #title，and，description
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          #重试次数
          MERGE_RETRIES: '0'
          #重试间隔10s
          MERGE_RETRY_SLEEP: '10000'
          #合并后删除分支
          MERGE_DELETE_BRANCH: 'true'
          MERGE_FILTER_AUTHOR: 'topsjf' 


