name: Auto Merge

on:
  #以下pr类型触发
  pull_request:
    types:
      - labeled
    #  - unlabeled
    #  - synchronize
    #  - opened
   #   - edited
    #  - ready_for_review
      - reopened
      - unlocked
  status: {}
  
jobs:
  automerge:    
    name: 合并PR
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: 开始合并
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
          MERGE_LABELS: ''
          #title，and，description
          MERGE_COMMIT_MESSAGE: "Merge PR(#{pullRequest.number}) {pullRequest.title}"
          #重试次数
          MERGE_RETRIES: '0'
          #重试间隔10s
          MERGE_RETRY_SLEEP: '10000'
          #合并后删除分支
          MERGE_DELETE_BRANCH: 'true'
          MERGE_FILTER_AUTHOR: 'topsjf' 


